import os
import gc
import random
import string
import pickle
import numpy as np
from hashlib import sha256
from joblib import Parallel, delayed
from .encoder import Encoder, normalize_joined_record
from .pairwise_set_metrics import assemble_pairwise_results, compute_set_metrics, make_inds


class TSHEncoder(Encoder):
    """A class that implements a column-based vector hashing approach for PPRL
       to encode strings into integer hash value sets.
    """

    def __init__(self, num_hash_funct, num_hash_col, ngram_size, rand_mode='PNG', secret=None, verbose=True, workers=-1,
                 seed=None):
        """To initialise the class we need to set the number of hash functions,
           the number of hash columns (bit arrays) to generate, the maximum
           integer for the random numbers to be generated, and a counter for
           which random value to be used in the final hash vector for each column.

           Input arguments:
             - num_hash_funct  The number of hash functions to be used to hash
                               each q-gram of an input q-grams set.
             - num_hash_col    The number of hash columns, i.e. bit arrays, to be
                               generated.
             - rand_mode       The random integer number generation mode, this can
                               either be generated using SHA-256 (SHA) or using a
                               pseudo random number generator (PNG).
           Output:
             - This method does not return anything.
        """

        assert num_hash_funct > 1, num_hash_funct
        assert num_hash_col > 1, num_hash_col
        assert rand_mode in ['PNG', 'SHA'], rand_mode

        self.num_hash_funct = num_hash_funct
        self.num_hash_col = num_hash_col
        self.rand_mode = rand_mode
        self.ngram_size = ngram_size
        self.range_p = 2 * ((2 ** num_hash_funct) - 1)
        if seed is not None:
            np.random.seed(seed=seed)
        self.hash_separators = np.random.randint(0, 2 ** 16, size=num_hash_funct).astype(str)
        self.salt = ''.join(random.choice(string.ascii_letters) for i in range(32)) if secret is None else secret
        self.verbose = verbose
        self.workers = os.cpu_count() if workers == -1 else workers

    # ---------------------------------------------------------------------------

    def enc(self, data):
        """Apply column-based vector hashing on the given input q-gram set and
           generate a hash value set which is returned.

           Input arguments:
             - q_gram_set  The set of q-grams (strings) to be encoded.

           Output:
             - hash_set  A set of hash values representing the q-gram set.
        """

        concat_lower = normalize_joined_record(data)
        # Split each string in the data into a list of qgrams to process
        q_gram_set = [concat_lower[i:i + self.ngram_size] for i in range(len(concat_lower) - self.ngram_size + 1)]

        hash_bitarray = np.zeros((self.num_hash_funct, self.num_hash_col), np.uint8)

        for q in q_gram_set:
            for hash_ind, sep in enumerate(self.hash_separators):
                hash_str = q + sep
                hash_bitarray[hash_ind, int(sha256(hash_str.encode()).hexdigest(), 16) % self.num_hash_col] = 1

        hash_set = list()

        for col_index in range(self.num_hash_col):
            if sum(hash_bitarray[:, col_index]) == 0:
                continue
            hash_str = "".join(list(hash_bitarray[:, col_index].astype(str))) + str(col_index) + self.salt
            if self.rand_mode == "PNG":
                # Compute ranges for integers generated by PRNG. See P. 144 of "Secure and Accurate
                # Two-Step Hash Encoding for Privacy-Preserving Record Linkage"
                # for explanation:  https://doi.org/10.1007/978-3-030-47436-2_11
                rand_min = (col_index - 1) * self.range_p
                rand_max = col_index * self.range_p - 1

                # rand_min = col_index * (2 ** self.num_hash_funct)
                # rand_max = rand_min + (2 ** self.num_hash_funct)

                random.seed(hash_str)
                hash_val = random.randint(rand_min, rand_max)
            else:
                hash_val = int(sha256(hash_str.encode()).hexdigest(), 16)
            hash_set.append(hash_val)

        return set(hash_set)

    def encode(self, data):
        if isinstance(data[0], list):
            return [self.enc(d) for d in data]
        else:
            return self.enc(data)

    def encode_and_compare_and_append(self, data, uids, metric, sim=True, store_encs=False):
        available_metrics = ["jaccard", "dice"]
        assert metric in available_metrics, "Invalid similarity metric. Must be one of " + str(available_metrics)
        numex = len(uids)
        uids_as_float = np.array(uids, dtype=np.float32)

        parallel = Parallel(n_jobs=self.workers)
        output_generator = parallel(delayed(self.enc)(i) for i in data)
        cache = {}
        encodings = []
        for i, enc in enumerate(output_generator):
            cache[uids_as_float[i]] = enc
            encodings.append(enc)
        combined_data = np.column_stack((data, encodings, uids))
        del output_generator, data

        gc.collect()

        if store_encs:
            tmpdict = dict()

            for key, val in cache.items():
                tmpdict[str(int(key))] = val
            with open("./graphMatching/data/encodings/encoding_dict.pck", "wb") as f:
                pickle.dump(tmpdict, f, pickle.HIGHEST_PROTOCOL)

            del tmpdict

        output_generator = parallel(delayed(make_inds)(i, numex) for i in np.array_split(np.arange(numex),
                                                                                         self.workers*4))
        inds = np.vstack(output_generator)
        inds = np.array_split(inds, self.workers)
        gc.collect()

        pw_metrics = parallel(delayed(compute_set_metrics)(i, cache, uids_as_float, metric, sim) for i in inds)
        pw_metrics = np.concatenate(pw_metrics, axis=None)
        del cache
        gc.collect()
        re = assemble_pairwise_results(inds, uids_as_float, pw_metrics)
        del pw_metrics
        gc.collect()
        del inds, uids_as_float
        gc.collect()
        # ...and add the metrics
        return re, combined_data

    def get_encoding_dict(self, data, uids):
        uids = np.array(uids, dtype=np.float32)

        parallel = Parallel(n_jobs=self.workers)
        output_generator = parallel(delayed(self.enc)(i) for i in data)
        cache = {}
        for i, enc in enumerate(output_generator):
            cache[uids[i]] = enc
        del output_generator, data
        gc.collect()

        tmpdict = dict()

        for key, val in cache.items():
            tmpdict[str(int(key))] = val

        return tmpdict
